### ISSUE TITLE
Not handling Managed Policy correctly.

### ISSUE THREAD

**Issue by dtvo2005** [awslabs/aws-iam-generator#16]
The template came from the script will not run in CloudFormation console when trying to creating a stack from it.  Syntax Error message for all managed policies when running this script.

**Comment by nhawkins04** [comment]
@dtvo2005 - Can you paste a sample configuration file for what you are trying to do? Are you referencing an AWS Managed Policy or a Customer Managed Policy? Are you creating the Managed Policy using the aws-iam-generator or referencing something which is existing?

**Comment by dtvo2005** [comment]
@nhawkins04 ,

First of all, thank you for replying.  Below is the sample of the config.yaml and the policy.  I am not using any Roles, Groups, Restriction, etc so the rest of are commented out in the config file.

Sample config.yaml:
    global:
  names:
    policies: True
    roles: True
    users: False
    groups: False
  template_outputs: True

accounts:
  sample-master:
    id: 111111111111
    parent: true
    saml_provider: ssoprod
  sample-infosec:
    id: 222222222222

policies:
  sample-emr-role:
    description: EMR role
    policy_file: emr_role.j2


Sample Policy:
    {
	"Version": "2012-10-17",
	"Statement": [{
		"Effect": "Allow",
		"Principal": {
			"Service": [
				"elasticmapreduce.amazonaws.com"
			]
		},
		"Action": [
			"sts:AssumeRole"
		]
	}],
	"ManagedPolicyArns": [
		"arn:aws:iam::aws:policy/service-role/AmazonElasticMapReduceRole"
	]
}

**Comment by nhawkins04** [comment]
Your sample policy is not valid is the issue here. I would recommend using the IAM policy generator and pasting that json in there and you can see what the errors are. ManagedPolicyArns, for example, is not a valid element for an IAM Policy: https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements.html

**Comment by dtvo2005** [comment]
Thanks,

I will take a look into this in the morning. Thank you so much for your time.
