### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by Marakai** [awslabs/aws-iam-generator#26]
Is this tool still maintained by awslabs? I find I still use it to automate all things IAM - it's just so clean and simple to use. Would hate for it to just die on the vine. Unless it's been surpassed by something better?

**Comment by yuft** [comment]
I guess AWS CDK is the future, see https://docs.aws.amazon.com/cdk/api/latest/docs/aws-iam-readme.html

**Comment by Marakai** [comment]
CDK still has a long way to go. Not to put too fine a point to it, at re:invent 2019 during a CFN chalk talk the consensus seemed to be, to quote one other attendee, "CDK is still a dumpster fire".

I'd agree that CDK should be the way to go, but at this time, there's too much missing.

**Comment by Marakai** [comment]
PS: after some time working with the latest CDK I have to say it's come a long way. That said, I still like aws-iam-generator and it's simple, logical configuration approach.

I think in my spare time, I'll see if I can't combine the best of both worlds and convert this to use CDK instead of troposphere, while keeping the nice YAML config plus Jinja2 approach (and switch it all to Python3 while I'm at it...).
