### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [awslabs/aws-iam-generator#6]
Hey, thanks for the great project!

I would like to try to add windows support, and it does not seem to be to difficult.

The `iam_template_build.py` already works! So, I can call it directly and I am already very happy.

The `build.py` does not work, so here my questions:

1. Why does the build.py even exist? Or why is it not just the `iam_template_build.py` directly? Why the detour via `build.py`?
2. Why are you calling `iam_template_build.py` via python from `build.py`? Could you not load  the file via `import` and then call the python code?

Thanks!

**Comment by apmclean** [comment]
I'll admit to the build.py part not being well thought through.  I copied it from another project I was doing where it did far more than call a single python file and never re-visited it.

I'd be delighted to see a PR for Windows support if you've got the cycles!

**Comment by RudolfVonKrugstein** [comment]
See https://github.com/awslabs/aws-iam-generator/pull/7

**Comment by apmclean** [comment]
Thanks again!
